<?php

/*
 * DESCRIPTION : Fonctions relatives à la barre d'outils 
 * 
 */
 
include ("../include/template.inc.php");
include ("../../../../configuration_w/constantesPHP.conf.php");
include ("../../../../configuration/label_".$_SESSION["sess_langue"].".conf");
include ("../../../../configuration/url.conf.php");
include ("../include/get_menu.php");

function parseXmlToolbar($t)
{   /*
if ($_SESSION["sess_droitGestListHier"] == true || $_SESSION["sess_droitGestDomainFerme"] == true ||
    $_SESSION["sess_droitAdminUtilisateur"] == true || $_SESSION["sess_droitThesaurus"] == true || 
    $_SESSION["sess_droitAdminProfilLR"] == true || count($_SESSION["sess_tab_profil_util_appli"]) > 1)
    $t->parse("bloc_parametrage", "BLOC_PARAMETRAGE");
else
    $t->set_var("bloc_parametrage", "");    
    */
$t->set_var("CST_LIBELLE_VERSION", CST_LIBELLE_VERSION);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_UTIL", CST_LIBELLE_TOOLBAR_GEST_UTIL);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_DOMAIN", CST_LIBELLE_TOOLBAR_GEST_DOMAIN);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_LISTHIER", CST_LIBELLE_TOOLBAR_GEST_LISTHIER);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_THESAURUS", CST_LIBELLE_TOOLBAR_GEST_THESAURUS);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_PROFIL_UTIL", CST_LIBELLE_TOOLBAR_GEST_PROFIL_UTIL);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_SESS_UTIL", CST_LIBELLE_TOOLBAR_GEST_SESS_UTIL);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_DOC_EN_MODIF", CST_LIBELLE_TOOLBAR_GEST_DOC_EN_MODIF);
// fonctions non disponibles
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_NATURE", CST_LIBELLE_TOOLBAR_GEST_NATURE);
$t->set_var("CST_LIBELLE_TOOLBAR_TYPES_DOC", CST_LIBELLE_TOOLBAR_TYPES_DOC);
$t->set_var("CST_LIBELLE_TOOLBAR_RUBRIQUES", CST_LIBELLE_TOOLBAR_RUBRIQUES);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_PROFIL_HIER", CST_LIBELLE_TOOLBAR_GEST_PROFIL_HIER);
$t->set_var("CST_LIBELLE_TOOLBAR_RECH_CLE", CST_LIBELLE_TOOLBAR_RECH_CLE);
$t->set_var("CST_LIBELLE_TOOLBAR_RECH_ELA", CST_LIBELLE_TOOLBAR_RECH_ELA);
$t->set_var("CST_LIBELLE_TOOLBAR_RECH_SIM", CST_LIBELLE_TOOLBAR_RECH_SIM);
$t->set_var("CST_LIBELLE_TOOLBAR_RECH_HIS_DOC", CST_LIBELLE_TOOLBAR_RECH_HIS_DOC);
$t->set_var("CST_LIBELLE_TOOLBAR_RECH_HIS_QUEST", CST_LIBELLE_TOOLBAR_RECH_HIS_QUEST);
$t->set_var("CST_LIBELLE_TOOLBAR_GEST_BIB", CST_LIBELLE_TOOLBAR_GEST_BIB);
$t->set_var("CST_LIBELLE_TOOLBAR_RECH_NUM", CST_LIBELLE_TOOLBAR_RECH_NUM);
$t->set_var("CST_LIBELLE_TOOLBAR_RECH_EXC_SIM", CST_LIBELLE_TOOLBAR_RECH_EXC_SIM);
$t->set_var("CST_LIBELLE_TOOLBAR_CREATION", CST_LIBELLE_TOOLBAR_CREATION);
$t->set_var("CST_LIBELLE_TOOLBAR_PASSWORD", CST_LIBELLE_TOOLBAR_PASSWORD);
    $t->set_var("CST_LIBELLE_TOOLBAR_GEST_PROFIL", CST_LIBELLE_TOOLBAR_GEST_PROFIL);
$t->set_var("CST_LIBELLE_TOOLBAR_STAT_ADMIN", CST_LIBELLE_TOOLBAR_STAT_ADMIN);
$t->set_var("URL_STAT_ADMIN", URL_AFFICHER_STATS_ADMIN);

$t->set_var("URL_VERSION", URL_VERSION);
$t->set_var("URL_AFFICHE_UTILISATEUR", URL_AFFICHE_UTILISATEUR);
$t->set_var("URL_AFFICHE_PROFIL_UTILISATEUR", URL_AFFICHE_PROFIL_UTILISATEUR);
$t->set_var("URL_LIST_RUB_DOMFERME", URL_LIST_RUB_DOMFERME);
$t->set_var("URL_LIST_LISTHIER", URL_LIST_LISTHIER);
$t->set_var("URL_LIST_THESAURUS", URL_LIST_THESAURUS);
$t->set_var("URL_AFFICHE_LIST_PROFILHIER", URL_AFFICHE_LIST_PROFILHIER);
$t->set_var("URL_LIST_NATURE", URL_LIST_NATURE);
$t->set_var("URL_LIST_TYPEDOC", URL_LIST_TYPEDOC);
$t->set_var("URL_LIST_RUBRIQUE", URL_LIST_RUBRIQUE);
$t->set_var("URL_AFFICHE_CONNEXION", URL_AFFICHE_CONNEXION);
$t->set_var("URL_AFFICHE_DOC_EN_MODIFICATION", URL_AFFICHE_DOC_EN_MODIFICATION);
$t->set_var("URL_CHOIX_TYPE_RECHERCHE_CLE", "../type/afficher_type.php?ACTION=RECHERCHE_CLE");
$t->set_var("URL_CHOIX_TYPE_RECHERCHE_ELABOREE", "../type/afficher_type.php?ACTION=RECHERCHE_ELA");
$t->set_var("URL_CHOIX_TYPE_RECHERCHE_SIMPLE", "../type/afficher_type.php?ACTION=RECHERCHE");
$t->set_var("URL_AFFICHE_HISTORIQUE", URL_AFFICHE_HISTORIQUE);
$t->set_var("URL_AFFICHE_HIST_QUESTION", URL_AFFICHE_HIST_QUESTION);
$t->set_var("URL_RECHERCHE_ELABOREE_ENREG_QUEST", URL_RECHERCHE_ELABOREE_ENREG_QUEST);
$t->set_var("URL_RECHERCHE_POS_NUM_DOC", URL_RECHERCHE_POS_NUM_DOC);
$t->set_var("URL_AFFICHER_RECHERCHE_FTX", URL_AFFICHER_RECHERCHE_FTX);
$t->set_var("URL_AFFICHER_CHANGER_PWD", URL_AFFICHER_CHANGER_PWD);
$t->set_var("URL_AFFICHE_GEST_PROFIL_LR", URL_AFFICHE_GEST_PROFIL_LR);
$t->set_var("URL_AFFICHER_RECHERCHE_SIMPLE", URL_RECHERCHE_SIMPLE);
$t->set_var("URL_AFFICHER_CREATION", URL_CREATION);
$t->set_var("URL_AFFICHE_QUEST_BIB", URL_AFFICHE_QUEST_BIB);
$t->set_var("URL_CHOIX_TYPE_CREATION", "../type/afficher_type.php?ACTION=CREATION");
$t->set_var("URL_FERMER_APPLICATION", URL_ATTENTE."?URL=../../../../interface/session/principal/connexion/close_deconnect.php&DECONNECT=1");
$t->set_var("URL_AFFICHER_QUESTION", URL_AFFICHER_QUESTION);
$t->set_var("URL_TOOLBAR", URL_TOOLBAR);
$t->set_var("URL_ATTENTE", URL_ATTENTE);
$t->set_var("URL_RESULTAT", URL_RESULTAT);
$t->set_var("URL_RECHERCHE_ELABOREE", URL_RECHERCHE_ELABOREE);

$t->set_var("LIBELLE_TOOLBAR_BLOC_ACCUEIL", CST_LIBELLE_TOOLBAR_BLOC_ACCUEIL);
$t->set_var("LIBELLE_TOOLBAR_BLOC_PARAMETRAGE", CST_LIBELLE_TOOLBAR_BLOC_PARAMETRAGE);
$t->set_var("LIBELLE_TOOLBAR_BLOC_RECHERCHE", CST_LIBELLE_TOOLBAR_BLOC_RECHERCHE);
$t->set_var("LIBELLE_TOOLBAR_FERMER", CST_LIBELLE_TOOLBAR_FERMER);

$t->set_var("USER_NAME", $_SESSION["sess_user_name"]);
$t->set_var("USER_PROFIL", $_SESSION["sess_profil"]);
$t->set_var("CST_LANG", $_SESSION["sess_langue"]);
    return $t->parse("Output", "toolbar"); 
}
?>
